import re

# Extract comments (with COMMENT keyword) from SQL commands and return them as a dict


def extract_comments(sql_commands):
    comments = {}
    comments_list = []
    for sql_command in sql_commands:
        sql_command.replace("\t", "")
        sql_command.strip()
        if "`" in sql_command:
            sql_command = sql_command.replace("`", "")
        table_name_match = ""
        if 'CREATE TABLE "' in sql_command:
            table_name_match = re.search(
                r'CREATE TABLE "(.*?)"', sql_command)
        else:
            table_name_match = re.search(
                r'CREATE TABLE (.*?)\s*\(', sql_command)
        if table_name_match:
            table_name = table_name_match.group(1)
            lines = sql_command.split("\n")
            for line in lines:
                if "COMMENT" in line:
                    column_name_match = re.search(r'"(\w+)"', line)
                    if not column_name_match:
                        column_name_match = re.search(r'(\w+)\s', line)
                    if column_name_match:
                        column_name = column_name_match.group(1)
                        comment_match = re.search(r"COMMENT '(\w+)'", line)
                        if comment_match:
                            comment = comment_match.group(1)
                            # print(table_name, column_name, comment)
                            if table_name not in comments:
                                comments[table_name] = {}
                            comments[table_name][column_name] = comment
                            comments_list.append(
                                {comment: table_name + "." + column_name})
    return comments, comments_list


if __name__ == "__main__":
    sql_commands = [
        '''CREATE TABLE `balance_sheet_CN_STOCK_A` (
                date DATE NOT NULL COMMENT '公告日', 
                instrument VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '股票代码', 
                report_date DATE NOT NULL COMMENT '报告期', 
                change_type INTEGER COMMENT '调整类型 0：未调整，1：调整过', 
                fs_quarter_index INTEGER COMMENT '对应季度', 
                account_receivable DOUBLE COMMENT '应收账款', 
                accounts_payable DOUBLE COMMENT '应付账款', 
                act_underwriting_sec DOUBLE COMMENT '代理承销证券款', 
                acting_td_sec DOUBLE COMMENT '代理买卖证券款', 
                actual_received_capital DOUBLE COMMENT '实收资本（或股本）', 
                advance_payment DOUBLE COMMENT '预收款项', 
                appropriative_reserve DOUBLE COMMENT '专项储备', 
                asset_diff_sri DOUBLE COMMENT '资产差额（特殊报表科目）', 
                asset_diff_tbi DOUBLE COMMENT '资产差额（合计平衡科目）', 
                bill_and_account_payable DOUBLE COMMENT '应付票据及应付账款', 
                bill_and_account_receivable DOUBLE COMMENT '应收票据及应收账款', 
                bill_payable DOUBLE COMMENT '应付票据', 
                bill_receivable DOUBLE COMMENT '应收票据', 
                bond_payable DOUBLE COMMENT '应付债券', 
                borrowing_funds DOUBLE COMMENT '拆入资金', 
                bs_other_compre_income DOUBLE COMMENT '其他综合收益', 
                buy_resale_fnncl_assets DOUBLE COMMENT '买入返售金融资产', 
                capital_reserve DOUBLE COMMENT '资本公积', 
                charge_and_commi_payable DOUBLE COMMENT '应付手续费及佣金', 
                construction_in_process DOUBLE COMMENT '在建工程', 
                construction_in_process_sum DOUBLE COMMENT '在建工程合计', 
                contract_asset DOUBLE COMMENT '合同资产', 
                contract_liab DOUBLE COMMENT '合同负债', 
                currency_fund DOUBLE COMMENT '货币资金', 
                debt_right_invest DOUBLE COMMENT '债权投资', 
                derivative_fnncl_assets DOUBLE COMMENT '衍生金融资产', 
                derivative_fnncl_liab DOUBLE COMMENT '衍生金融负债', 
                dev_expenditure DOUBLE COMMENT '开发支出', 
                differed_income_current_liab DOUBLE COMMENT '递延收益-流动负债', 
                differed_incomencl DOUBLE COMMENT '递延收益-非流动负债', 
                divided_into_asset_for_sale DOUBLE COMMENT '持有待售资产', 
                divided_into_liab_for_sale DOUBLE COMMENT '持有待售负债', 
                dividend_payable DOUBLE COMMENT '应付股利', 
                dividend_receivable DOUBLE COMMENT '应收股利', 
                dt_assets DOUBLE COMMENT '递延所得税资产', 
                dt_liab DOUBLE COMMENT '递延所得税负债', 
                earned_surplus DOUBLE COMMENT '盈余公积', 
                equity_right_diff_tbi DOUBLE COMMENT '股权权益差额（合计平衡科目）', 
                estimated_liab DOUBLE COMMENT '预计负债', 
                fa_calc_by_amortized_cost DOUBLE COMMENT '以摊余成本计量的金融资产', 
                fixed_asset DOUBLE COMMENT '固定资产', 
                fixed_asset_sum DOUBLE COMMENT '固定资产合计', 
                fixed_assets_disposal DOUBLE COMMENT '固定资产清理', 
                flow_assets_diff_sri DOUBLE COMMENT '流动资产差额（特殊报表科目）', 
                flow_assets_diff_tbi DOUBLE COMMENT '流动资产差额（合计平衡科目）', 
                flow_debt_diff_sri DOUBLE COMMENT '流动负债差额（特殊报表科目）', 
                flow_debt_diff_tbi DOUBLE COMMENT '流动负债差额（合计平衡科目）', 
                fnncl_assets_sold_for_repur DOUBLE COMMENT '卖出回购金融资产款', 
                frgn_currency_convert_diff DOUBLE COMMENT '外币报表折算差额', 
                general_risk_provision DOUBLE COMMENT '一般风险准备', 
                goodwill DOUBLE COMMENT '商誉', 
                held_to_maturity_invest DOUBLE COMMENT '持有至到期投资', 
                holder_equity_diff_sri DOUBLE COMMENT '股东权益差额（特殊报表科目）', 
                insurance_contract_reserve DOUBLE COMMENT '保险合同准备金', 
                intangible_assets DOUBLE COMMENT '无形资产', 
                interest_payable DOUBLE COMMENT '应付利息', 
                interest_receivable DOUBLE COMMENT '应收利息', 
                inventory DOUBLE COMMENT '存货', 
                invest_property DOUBLE COMMENT '投资性房地产', 
                lease_libilities DOUBLE COMMENT '租赁负债', 
                lending_fund DOUBLE COMMENT '拆出资金', 
                liab_and_equity_diff_sri DOUBLE COMMENT '负债及股东权益差额（特殊报表科目）', 
                liab_and_equity_diff_tbi DOUBLE COMMENT '负债及股东权益差额（合计平衡科目）', 
                liab_diff_sri DOUBLE COMMENT '负债差额（特殊报表科目）', 
                liab_diff_tbi DOUBLE COMMENT '负债差额（合计平衡科目）', 
                loan_from_central_bank DOUBLE COMMENT '向中央银行借款', 
                loans_and_payments DOUBLE COMMENT '发放贷款及垫款', 
                `It_deferred_expense` DOUBLE COMMENT '长期待摊费用', 
                `It_equity_invest` DOUBLE COMMENT '长期股权投资', 
                `It_loan` DOUBLE COMMENT '长期借款', 
                `It_payable` DOUBLE COMMENT '长期应付款', 
                `It_payable_sum` DOUBLE COMMENT '长期应付款合计', 
                `It_receivable` DOUBLE COMMENT '长期应收款', 
                `It_staff_salary_payable` DOUBLE COMMENT '长期应付职工薪酬', 
                minority_equity DOUBLE COMMENT '少数股东权益', 
                noncurrent_asset_due_within1y DOUBLE COMMENT '一年内到期的非流动资产', 
                noncurrent_assets_diff_sri DOUBLE COMMENT '非流动资产差额（特殊报表科目）', 
                noncurrent_assets_diff_tbi DOUBLE COMMENT '非流动资产差额（合计平衡科目）', 
                noncurrent_liab_diff_sbi DOUBLE COMMENT '非流动负债差额（合计平衡科目）', 
                noncurrent_liab_diff_sri DOUBLE COMMENT '非流动负债差额（特殊报表科目）', 
                noncurrent_liab_due_in1y DOUBLE COMMENT '一年内到期的非流动负债', 
                oil_and_gas_asset DOUBLE COMMENT '油气资产', 
                other_compre_fa_by_fv DOUBLE COMMENT '以公允价值计量且其变动计入其他综合收益的金融资产', 
                other_cunrren_assets DOUBLE COMMENT '其他流动资产', 
                other_current_liab DOUBLE COMMENT '其他流动负债', 
                other_debt_right_invest DOUBLE COMMENT '其他债权投资', 
                other_ei_invest DOUBLE COMMENT '其他权益工具投资', 
                other_equity_instruments DOUBLE COMMENT '其他权益工具', 
                other_payables DOUBLE COMMENT '其他应付款', 
                other_payables_sum DOUBLE COMMENT '其他应付款合计', 
                other_receivables DOUBLE COMMENT '其他应收款', 
                other_receivables_sum DOUBLE COMMENT '其他应收款合计', 
                other_uncurrent_fa DOUBLE COMMENT '其他非流动金融资产', 
                othr_noncurrent_assets DOUBLE COMMENT '其他非流动资产', 
                othr_noncurrent_liab DOUBLE COMMENT '其他非流动负债', 
                payroll_payable DOUBLE COMMENT '应付职工薪酬', 
                perpetual_capital_sec DOUBLE COMMENT '永续债', 
                preferred_shares DOUBLE COMMENT '其中优先股', 
                preferred DOUBLE COMMENT '优先股', 
                premium_receivable DOUBLE COMMENT '应收保费', 
                prepays DOUBLE COMMENT '预付款项', 
                productive_biological_assets DOUBLE COMMENT '生产性生物资产', 
                project_goods_and_material DOUBLE COMMENT '工程物资', 
                receivable_financing DOUBLE COMMENT '应收款项融资', 
                rein_account_receivable DOUBLE COMMENT '应收分保账款', 
                rein_contract_reserve DOUBLE COMMENT '应收分保合同准备金', 
                rein_payable DOUBLE COMMENT '应付分保账款', 
                right_of_use_assets DOUBLE COMMENT '使用权资产', 
                saleable_finacial_assets DOUBLE COMMENT '可供出售金融资产', 
                saving_and_interbank_deposit DOUBLE COMMENT '吸收存款及同业存放', 
                settle_reserves DOUBLE COMMENT '结算备付金', 
                special_payable DOUBLE COMMENT '专项应付款', 
                st_bond_payable DOUBLE COMMENT '应付短期债券', 
                st_borrow DOUBLE COMMENT '短期借款', 
                tax_payable DOUBLE COMMENT '应交税费', 
                total_assets DOUBLE COMMENT '资产总计', 
                total_current_assets DOUBLE COMMENT '流动资产合计', 
                total_current_liab DOUBLE COMMENT '流动负债合计', 
                total_equity_atoopc DOUBLE COMMENT '归属于母公司所有者权益合计', 
                total_liab_and_owner_equity DOUBLE COMMENT '负债和所有者权益总计', 
                total_liab DOUBLE COMMENT '负债合计', 
                total_noncurrent_assets DOUBLE COMMENT '非流动资产合计', 
                total_noncurrent_liab DOUBLE COMMENT '非流动负债合计', 
                total_owner_equity DOUBLE COMMENT '所有者权益合计', 
                tradable_fnncl_assets DOUBLE COMMENT '交易性金融资产', 
                tradable_fnncl_liab DOUBLE COMMENT '交易性金融负债', 
                treasury_stock DOUBLE COMMENT '库存股', 
                undstrbtd_profit DOUBLE COMMENT '未分配利润', 
                PRIMARY KEY (date, instrument, report_date)
            )DEFAULT CHARSET=utf8mb4 COMMENT='资产负债表' ENGINE=InnoDB COLLATE utf8mb4_unicode_ci''',
        '''CREATE TABLE basic_info_CN_STOCK_A (
                instrument VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '证券代码', 
                delist_date DATE COMMENT '退市日期，如果未退市，则为pandas.NaT', 
                company_type VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '公司类型', 
                company_name VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '公司名称', 
                company_province VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '公司省份', 
                list_board VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '上市板', 
                company_found_date DATETIME COMMENT '公司成立日期', 
                name VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '证券名称', 
                list_date DATE COMMENT '上市日期', 
                PRIMARY KEY (instrument)
            )COMMENT='A股股票基本信息' DEFAULT CHARSET=utf8mb3 ENGINE=InnoDB''',
        """CREATE TABLE `cash_flow_CN_STOCK_A` (
                date DATE COMMENT '公告日',
                instrument VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '股票代码',
                report_date DATE COMMENT '报告期',
                change_type INTEGER COMMENT '调整类型 0：未调整，1：调整过',
                fs_quarter_index INTEGER COMMENT '对应季度',
                asset_impairment_reserve DOUBLE COMMENT '资产减值准备',
                borrowing_net_add_central_bank DOUBLE COMMENT '向中央银行借款净增加额',
                borrowing_net_increase_amt DOUBLE COMMENT '拆入资金净增加额',
                cash_of_orig_ic_indemnity DOUBLE COMMENT '支付原保险合同赔付款项的现金',
                cash_paid_for_assets DOUBLE COMMENT '购建固定资产、无形资产和其他长期资产支付的现金',
                cash_paid_for_interests_etc DOUBLE COMMENT '支付利息、手续费及佣金的现金',
                cash_paid_for_pd DOUBLE COMMENT '支付保单红利的现金',
                cash_paid_of_distribution DOUBLE COMMENT '分配股利、利润或偿付利息支付的现金',
                cash_paid_to_staff_etc DOUBLE COMMENT '支付给职工以及为职工支付的现金',
                cash_pay_for_debt DOUBLE COMMENT '偿还债务支付的现金',
                cash_received_from_bond_issue DOUBLE COMMENT '发行债券收到的现金',
                cash_received_from_orig_ic DOUBLE COMMENT '收到原保险合同保费取得的现金',
                cash_received_of_absorb_invest DOUBLE COMMENT '吸收投资收到的现金',
                cash_received_of_borrowing DOUBLE COMMENT '取得借款收到的现金',
                cash_received_of_dspsl_invest DOUBLE COMMENT '收回投资收到的现金',
                cash_received_of_interest_etc DOUBLE COMMENT '收取利息、手续费及佣金的现金',
                cash_received_of_other_fa DOUBLE COMMENT '收到其他与投资活动有关的现金',
                cash_received_of_other_oa DOUBLE COMMENT '收到其他与经营活动有关的现金',
                cash_received_of_othr_fa DOUBLE COMMENT '收到其他与筹资活动有关的现金',
                cash_received_of_sales_service DOUBLE COMMENT '销售商品、提供劳务收到的现金',
                cb_due_within1y DOUBLE COMMENT '一年内到期的可转换公司债券',
                cce_net_add_amt_diff_sri_dm DOUBLE COMMENT '直接法—现金及现金等价物净增加额差额（特殊报表科目）',
                cce_net_add_amt_diff_tbi_dm DOUBLE COMMENT '直接法—现金及现金等价物净增加额差额（合计平衡科目）',
                cce_net_add_diff_im_sri DOUBLE COMMENT '间接法—现金及现金等价物净增加额差额（特殊报表科目）',
                cce_net_add_diff_im_tbi DOUBLE COMMENT '间接法—现金及现金等价物净增加额差额（合计平衡科目）',
                cr_from_minority_holders DOUBLE COMMENT '子公司吸收少数股东投资收到的现金',
                credit_impairment_loss DOUBLE COMMENT '信用减值损失',
                dap_paid_to_minority_holder DOUBLE COMMENT '子公司支付给少数股东的股利、利润',
                debt_tranfer_to_capital DOUBLE COMMENT '债务转为资本',
                deposit_and_interbank_net_add DOUBLE COMMENT '客户存款和同业存放款项净增加额',
                depreciation_etc DOUBLE COMMENT '固定资产折旧、油气资产折耗、生产性生物资产折旧',
                dt_assets_decrease DOUBLE COMMENT '递延所得税资产减少',
                dt_liab_increase DOUBLE COMMENT '递延所得税负债增加',
                effect_of_exchange_chg_on_cce DOUBLE COMMENT '汇率变动对现金及现金等价物的影响',
                ending_balance_of_cash DOUBLE COMMENT '现金的期末余额',
                fa_cash_in_flow_diff_sri DOUBLE COMMENT '筹资活动现金流入差额（特殊报表科目）',
                fa_cash_in_flow_diff_tbi DOUBLE COMMENT '筹资活动现金流入差额（合计平衡科目）',
                fa_cash_out_flow_diff_sri DOUBLE COMMENT '筹资活动现金流出差额（特殊报表科目）',
                fa_cash_out_flow_diff_tbi DOUBLE COMMENT '筹资活动现金流出差额（合计平衡科目）',
                final_balance_of_cce DOUBLE COMMENT '期末现金及现金等价物余额',
                finance_cost_cfs DOUBLE COMMENT '现金流量表—财务费用',
                finance_lease_fixed_assets DOUBLE COMMENT '融资租入固定资产',
                fixed_assets_scrap_loss DOUBLE COMMENT '固定资产报废损失',
                goods_buy_and_service_cash_pay DOUBLE COMMENT '购买商品、接受劳务支付的现金',
                ia_cash_inflow_diff_sri DOUBLE COMMENT '投资活动现金流入差额（特殊报表科目）',
                ia_cash_inflow_diff_tbi DOUBLE COMMENT '投资活动现金流入差额（合计平衡科目）',
                ia_cash_outflow_diff_sri DOUBLE COMMENT '投资活动现金流出差额（特殊报表科目）',
                ia_cash_outflow_diff_tbi DOUBLE COMMENT '投资活动现金流出差额（合计平衡科目）',
                increase_of_operating_item DOUBLE COMMENT '经营性应付项目的增加',
                initial_balance_of_cash DOUBLE COMMENT '现金的期初余额',
                initial_balance_of_cce DOUBLE COMMENT '现金等价物的期初余额',
                initial_cce_balance DOUBLE COMMENT '期初现金及现金等价物余额',
                intangible_assets_amortized DOUBLE COMMENT '无形资产摊销',
                inventory_decrease DOUBLE COMMENT '存货的减少',
                invest_income_cash_received DOUBLE COMMENT '取得投资收益收到的现金',
                invest_loss DOUBLE COMMENT '投资损失',
                invest_paid_cash DOUBLE COMMENT '投资支付的现金',
                lending_net_add_other_org DOUBLE COMMENT '向其他金融机构拆入资金净增加额',
                loan_and_advancenet_add DOUBLE COMMENT '客户贷款及垫款净增加额',
                loss_from_fv_chg DOUBLE COMMENT '公允价值变动损失',
                loss_of_disposal_assets DOUBLE COMMENT '处置固定资产、无形资产和其他长期资产的损失',
                `It_deferred_expenses_amrtzt` DOUBLE COMMENT '长期待摊费用摊销',
                naa_of_cb_and_interbank DOUBLE COMMENT '存放中央银行和同业款项净增加额',
                naa_of_disposal_fnncl_assets DOUBLE COMMENT '处置以公允价值计量且其变动计入当期损益的金融资产净增加额',
                naaassured_saving_and_invest DOUBLE COMMENT '保户储金及投资款净增加额',
                ncf_diff_from_fa_sri DOUBLE COMMENT '筹资活动产生的现金流量净额差额（特殊报表科目）',
                ncf_diff_from_fa_tbi DOUBLE COMMENT '筹资活动产生的现金流量净额差额（合计平衡科目）',
                ncf_diff_from_ia_sri DOUBLE COMMENT '投资活动产生的现金流量净额差额（特殊报表科目）',
                ncf_diff_from_ia_tbi DOUBLE COMMENT '投资活动产生的现金流量净额差额（合计平衡科目）',
                ncf_diff_from_oa_im_sri DOUBLE COMMENT '间接法—经营活动现金流量净额差额（特殊报表科目）',
                ncf_diff_from_oa_im_tbi DOUBLE COMMENT '间接法—经营活动现金流量净额差额（合计平衡科目）',
                ncf_diff_of_oa_sri DOUBLE COMMENT '经营活动产生的现金流量净额差额（特殊报表科目）',
                ncf_diff_of_oa_tbi DOUBLE COMMENT '经营活动产生的现金流量净额差额（合计平衡科目）',
                ncf_from_fa DOUBLE COMMENT '筹资活动产生的现金流量净额',
                ncf_from_ia DOUBLE COMMENT '投资活动产生的现金流量净额',
                ncf_from_oa_im DOUBLE COMMENT '间接法—经营活动产生的现金流量净额',
                ncf_from_oa DOUBLE COMMENT '经营活动产生的现金流量净额',
                net_add_in_pledge_loans DOUBLE COMMENT '质押贷款净增加额',
                net_add_in_repur_capital DOUBLE COMMENT '回购业务资金净增加额',
                net_cash_amt_from_branch DOUBLE COMMENT '取得子公司及其他营业单位支付的现金净额',
                net_cash_of_disposal_assets DOUBLE COMMENT '处置固定资产、无形资产和其他长期资产收回的现金净额',
                net_cash_of_disposal_branch DOUBLE COMMENT '处置子公司及其他营业单位收到的现金净额',
                net_cash_received_from_rein DOUBLE COMMENT '收到再保业务现金净额',
                net_increase_in_cce_im DOUBLE COMMENT '间接法—现金及现金等价物净增加额',
                net_increase_in_cce DOUBLE COMMENT '现金及现金等价物净增加额',
                np_cfs DOUBLE COMMENT '现金流量表-净利润',
                oa_cash_inflow_diff_sri DOUBLE COMMENT '经营活动现金流入差额（特殊报表科目）',
                oa_cash_inflow_diff_tbi DOUBLE COMMENT '经营活动现金流入差额（合计平衡科目）',
                oa_cash_outflow_diff_sri DOUBLE COMMENT '经营活动现金流出差额（特殊报表科目）',
                oa_cash_outflow_diff_tbi DOUBLE COMMENT '经营活动现金流出差额（合计平衡科目）',
                operating_items_decrease DOUBLE COMMENT '经营性应收项目的减少',
                other_cash_paid_related_to_ia DOUBLE COMMENT '支付其他与投资活动有关的现金',
                other_cash_paid_related_to_oa DOUBLE COMMENT '支付其他与经营活动有关的现金',
                othrcash_paid_relating_to_fa DOUBLE COMMENT '支付其他与筹资活动有关的现金',
                payments_of_all_taxes DOUBLE COMMENT '支付的各项税费',
                refund_of_tax_and_levies DOUBLE COMMENT '收到的税费返还',
                si_final_balance_of_cce DOUBLE COMMENT '现金等价物的期末余额',
                si_other DOUBLE COMMENT '其他',
                sub_total_of_ci_from_fa DOUBLE COMMENT '筹资活动现金流入小计',
                sub_total_of_ci_from_ia DOUBLE COMMENT '投资活动现金流入小计',
                sub_total_of_ci_from_oa DOUBLE COMMENT '经营活动现金流入小计',
                sub_total_of_cos_from_fa DOUBLE COMMENT '筹资活动现金流出小计',
                sub_total_of_cos_from_ia DOUBLE COMMENT '投资活动现金流出小计',
                sub_total_of_cos_from_oa DOUBLE COMMENT '经营活动现金流出小计'
            ) COLLATE utf8mb4_unicode_ci ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '现金流量表'""",
        """CREATE TABLE `income_CN_STOCK_A` (
                date DATE COMMENT '日期',
                instrument VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '股票代码',
                report_date DATE COMMENT '报告期',
                change_type INTEGER COMMENT '调整类型 (0: 未调整, 1: 调整过)',
                fs_quarter_index INTEGER COMMENT '对应季度',
                amortized_cost_fnncl_ass_cfrm DOUBLE COMMENT '以摊余成本计量的金融资产终止确认收益',
                asset_change_due_to_remeasure DOUBLE COMMENT '重新计量设定受益计划净负债或净资产的变动',
                asset_disposal_gain DOUBLE COMMENT '资产处置收益',
                asset_impairment_loss DOUBLE COMMENT '资产减值损失',
                basic_eps DOUBLE COMMENT '基本每股收益',
                cannt_reclass_gal_equity_law DOUBLE COMMENT '权益法下在被投资单位不能重分类进损益的其他综合收益中享有的份额',
                cannt_reclass_to_gal DOUBLE COMMENT '以后不能重分类进损益的其他综合收益',
                cash_flow_hedge_reserve DOUBLE COMMENT '现金流量套期储备',
                cf_hedging_gal_valid_part DOUBLE COMMENT '现金流量套期损益的有效部分',
                charge_and_commi_expenses DOUBLE COMMENT '手续费及佣金支出',
                commi_on_insurance_policy DOUBLE COMMENT '保单红利支出',
                compensate_net_pay DOUBLE COMMENT '赔付支出净额',
                continued_operating_np DOUBLE COMMENT '（一）持续经营净利润',
                corp_credit_risk_fvc DOUBLE COMMENT '企业自身信用风险公允价值变动',
                credit_impairment_loss DOUBLE COMMENT '信用减值损失',
                dlt_earnings_per_share DOUBLE COMMENT '稀释每股收益',
                earned_premium DOUBLE COMMENT '已赚保费',
                exchange_gain DOUBLE COMMENT '汇兑收益',
                extract_ic_reserve_net_amt DOUBLE COMMENT '提取保险合同准备金净额',
                fa_reclassi_amt DOUBLE COMMENT '金融资产重分类计入其他综合收益的金额',
                fc_convert_diff DOUBLE COMMENT '外币财务报表折算差额',
                fc_interest_income DOUBLE COMMENT '财务费用：利息收入',
                fee_and_commi_income DOUBLE COMMENT '手续费及佣金收入',
                financing_expenses DOUBLE COMMENT '财务费用',
                fv_chg_income DOUBLE COMMENT '公允价值变动收益',
                ii_from_jc_etc DOUBLE COMMENT '对联营企业和合营企业的投资收益',
                income_tax_cost DOUBLE COMMENT '所得税费用',
                interest_fee DOUBLE COMMENT '财务费用：利息费用',
                interest_income DOUBLE COMMENT '利息收入',
                interest_payout DOUBLE COMMENT '利息支出',
                invest_income DOUBLE COMMENT '投资收益',
                manage_fee DOUBLE COMMENT '管理费用',
                minority_gal DOUBLE COMMENT '少数股东损益',
                net_open_hedge_income DOUBLE COMMENT '净敞口套期收益',
                non_operating_income DOUBLE COMMENT '营业外收入',
                noncurrent_asset_dispose_gain DOUBLE COMMENT '非流动资产处置利得',
                noncurrent_asset_dispose_loss DOUBLE COMMENT '非流动资产处置损失',
                nonoperating_cost DOUBLE COMMENT '营业外支出',
                np_atoopc DOUBLE COMMENT '归属于母公司所有者的净利润',
                np_diff_sri DOUBLE COMMENT '净利润差额（特殊报表科目）',
                np_diff_tbi DOUBLE COMMENT '净利润差额（合计平衡科目）',
                op_diff_sri DOUBLE COMMENT '营业利润差额（特殊报表科目）',
                op_diff_tbi DOUBLE COMMENT '营业利润差额（合计平衡科目）',
                operating_cost_diff_sri DOUBLE COMMENT '营业支出（特殊报表科目）',
                operating_cost_diff_tbi DOUBLE COMMENT '营业支出（合计平衡项目）',
                operating_cost DOUBLE COMMENT '营业成本',
                operating_revenue_diff_sri DOUBLE COMMENT '营业收入（特殊报表科目）',
                operating_revenue_diff_tbi DOUBLE COMMENT '营业收入（合计平衡项目）',
                operating_taxes_and_surcharge DOUBLE COMMENT '税金及附加',
                operating_total_cost DOUBLE COMMENT '营业总成本',
                operating_total_revenue DOUBLE COMMENT '营业总收入',
                other_compre_income DOUBLE COMMENT '其他综合收益',
                other_debt_right_invest_fvc DOUBLE COMMENT '其他债权投资公允价值变动',
                other_debt_right_invest_ir DOUBLE COMMENT '其他债权投资信用减值准备',
                other_equity_invest_fvc DOUBLE COMMENT '其他权益工具投资公允价值变动',
                other_income DOUBLE COMMENT '其他收益',
                other_not_reclass_to_gal DOUBLE COMMENT '其他以后不能重分类进损益',
                other_reclass_to_gal DOUBLE COMMENT '其他以后将重分类进损益',
                othrcompre_income_atms DOUBLE COMMENT '归属于少数股东的其他综合收益',
                othrcompre_income_atoopc DOUBLE COMMENT '归属母公司所有者的其他综合收益',
                rad_cost_sum DOUBLE COMMENT '研发费用',
                reclass_and_salable_gal DOUBLE COMMENT '持有至到期投资重分类为可供出售金融资产损益',
                reclass_to_gal DOUBLE COMMENT '以后将重分类进损益的其他综合收益',
                reclass_togal_in_equity_law DOUBLE COMMENT '权益法下在被投资单位以后将重分类进损益的其他综合收益中享有的份额',
                refunded_premium DOUBLE COMMENT '退保金',
                rein_expenditure DOUBLE COMMENT '分保费用',
                revenue DOUBLE COMMENT '营业收入',
                saleable_fv_chg_gal DOUBLE COMMENT '可供出售金融资产公允价值变动损益',
                sales_fee DOUBLE COMMENT '销售费用',
                stop_operating_np DOUBLE COMMENT '（二）终止经营净利润',
                total_compre_income_atsopc DOUBLE COMMENT '归属于母公司股东的综合收益总额',
                total_compre_income DOUBLE COMMENT '综合收益总额',
                total_profit_diff_sri DOUBLE COMMENT '利润总额差额（特殊报表科目）',
                total_profit_diff_tbi DOUBLE COMMENT '利润总额差额（合计平衡科目）',
                total_profit DOUBLE COMMENT '利润总额'
            ) COLLATE utf8mb4_unicode_ci ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '利润表'"""
    ]

    comments, comments_list = extract_comments(sql_commands)
    print(comments)
    print(comments_list)
